docs/intro.md, docusaurus.config.js, src/pages/index.tsx
Updates the `intro.md` file as well as updates some of the site metadata
=> feat: update recipe intro and some metadata

docs/TypeScriptBaseURL.md
=> Added TypeScript baseUrl recipe

docs/intro.md, docusaurus.config.js
Updated the links pointing to the repo for the cookbook and for ignite. Also added some verbiage on submitting a recipe.
=> feat: update github links and add verbiage on submitting recipe idea

docs/MigratingToFlashList.md, docs/MigratingToMMKV.md, docusaurus.config.js, src/css/custom.css
- Closes #9 
- Adds colored syntax highlighting if needed via
```tsx
// error-line
return new Error("ThisWillBeHighlightedRed");
```
```tsx
// success-line
return true; // this will be highlighted in green
```
Example:
=> Recipe: Migrating from AsyncStorage to MMKV

docs/EnvironmentVariables.md
this do not sparks joy
this does
=> Add love to setup with docusorus copy icon

docusaurus.config.js
- updated the react native newsletter link from `https://reactnative.cc` to `https://reactnativenewsletter.com`
=> fix: update react native newsletter link

docs/ExpoUpdates.md, docs/PristineExpoProject.md
- Closes #35 
- Guide on how to set up Expo Updates in Android
=> feat(expo-updates): new recipe for expo-updates

src/components/HomepageFeatures/styles.module.css, src/css/custom.css
The landing page needed some love to make it look great on mobile! This is just some updates to help that happen
https://user-images.githubusercontent.com/8878532/211417387-22ff12f2-28d1-47df-9d82-a9c562cef5aa.mov
=> fix: responsiveness on the landing page

src/components/HomepageFeatures/styles.module.css, src/css/custom.css, src/pages/index.module.css, src/pages/index.tsx
Quick update of some of the styles. Trying to avoid using the `[class^='']` selector and changing it to `[class*='']` when it's necessary because of generated elements and styles. Styles should all look the same.
=> feat: css cleanup

.github/ISSUE_TEMPLATE/recipe_idea.yml, docs/recipes/ExpoUpdates.md, docusaurus.config.js, src/components/HomepageFeatures/styles.module.css, src/pages/index.module.css, src/pages/index.tsx
This PR adds a section at the bottom of the landing page that lists out the most recent 4 recipes and links to them.
https://user-images.githubusercontent.com/8878532/213569771-5b14e8ff-f01e-404a-9fd8-276c794f2bfb.mov
https://user-images.githubusercontent.com/8878532/213569793-6edf25b1-f5d4-4ef1-89aa-ddd0a640fe2a.mov
=> feat: fresh recipes section

src/pages/index.tsx
Updates with latest ignite release
=> feat: updated ignite release

docusaurus.config.js, package.json, src/css/custom.css, yarn.lock
This PR brings in local search with [docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local). Pretty much everything comes built in. It indexes during the build so search doesn't work locally unless you run `yarn build` then `yarn serve`
Currently I've disabled search on mobile because the user experience was pretty bad.
Also a few style changes to bring more in line with our theming:
https://user-images.githubusercontent.com/8878532/214669105-a8c466e6-3b6f-4d5b-8586-088d5bc93f51.mov
=> feat: local search

README.md, docusaurus.config.js
updates the baseUrl to be `/` instead of `/ignite-cookbook/`
=> feat: updates baseUrl

docs/recipes/SelectFieldWithBottomSheet.mdx, docusaurus.config.js, package.json, src/pages/index.tsx, yarn.lock
This recipe is to provide an option/answer to the question here: https://github.com/infinitered/ignite/discussions/2366 .
It adds a guide to wrap the TextField component to be used as a SelectField / Picker .
This PR also adds a video player in case people want to embed videos in the cookbook.
https://user-images.githubusercontent.com/1775841/219038677-bcc9c61d-1776-4aad-bb50-1e932721bc04.mp4
=> Adds a recipe for SelectField / Picker.

docs/recipes/DetoxIntro.md
This PR fixes the urls in the [Detox Intro recipe](https://ignitecookbook.com/docs/recipes/DetoxIntro)
=> Fix broken links in detox recipe

src/pages/index.tsx
Would be fun to ChatGPT session and automate this kind of change on the ignite repo publish
=> chore: update ignite release

docs/recipes/DistributingAuthTokenToAPI.md
What is this PR?
This PR adds a new recipe that explains the easy distribution of an auth token to an api to allow for authenticated requests. This comes on the heels of [this](https://infiniteredcommunity.slack.com/archives/CLTFW1NES/p1683219929265939) community slack thread and this pattern being used on at least 2 IR client projects. 
This is my first cookbook PR and recipe so I'd love any and all feedback!
=> Feat: Distributing Auth Token

src/pages/index.tsx
Points to latest Ignite v8.8.3
=> Updates to ignite v8.8.3

docs/recipes/StayingWithExpo.md
Following up with a conversation from https://community.infinite.red/
> How do I generate a development build of expo with Ignite?
=> feat: add eas init for the very first setup

src/pages/index.tsx
=> chore: Updated copy for v9.0.0 - Expresso

src/pages/index.tsx
- Bumps ignite version to 9.0.3
- Sets release date
=> chore: bump ignite 9.0.3

src/pages/index.tsx
=> chore: roll version and release date

README.md
Added a logo source compatible with light mode for @morganick 😄
=> README logo theme support

README.md
I noticed that some of the links in the project `README` were out of date or weren't featuring some of the newer recipes!
=> Updates recipe links in README.md

docs/recipes/RequiringHardwareFeaturesWithExpo.md
Thanks to @jbseppanen for pointing this out to me in the IR Community Slack!
=> fix(recipe): Fix the comments in the new requiring hardware with expo recipe.

docs/recipes/UpdatingIgnite.md
because
Many React Native developers asks this question:
> How can I update my Ignite boilerplate with the latest changes from the Ignite boilerplate?
=> feat(recipes): how to update ignite closes #118

docs/recipes/LocalFirstDataWithPowerSync.md
* Adds a recipe for using Powersync and Supabase to manage your app's state.
* This is a fairly lengthy recipe because it needs to include instructions for supabase authentication as well. These can likely be extracted to a separate "Authentication with Supabase" recipe which we can then reference in this one.
1. **Introduction**
2. **Prerequisites**
3. **Installing SDK and Dependencies**
4. **Authenticating with Supabase**
5. **Connecting PowerSync to Supabase**
6. **Managing Lists of Todos**
7.  **Viewing and Editing Individual TodoLists**
8. **Congratulations!**
* **Introduction**
* What is PowerSync?
* Benefits of Using PowerSync
* Using Other Backends
* **Prerequisites**
* **Installing SDK and Dependencies**
* Install necessary dependencies for PowerSync.
* Install necessary …
=> feat(recipes): powersync and supabase for local-first data management

docs/recipes/MigratingToMMKV.md
- Adds a warning about `react-native-mmkv` version for new architecture
=> fix(mmkv): new arch warning

docs/recipes/ExpoRouter.md
- Replaces the necessary gesture handler provider in main `_layout.tsx` that was missed
=> fix(expo-router): add gesture handler root view provider

CONTRIBUTING.md, docs/recipes/AccessibilityFontSizes.md, docs/recipes/Authentication.md, docs/recipes/ExpoRouter.md, docs/recipes/Redux.md, docs/recipes/UnrenderedItemInScrollView.md, docs/recipes/Zustand.md
PR addresses two issues:
- Syntax Highlighting
- Add titles to code blocks
=> Refactor docs to improve syntax highlighting and add titles to code blocks

docs/recipes/UniversalE2ETesting.md
This PR adds a recipe for Universal E2E Testing with Detox and Playwright. 
You can read it in [GitHub with a nicer markdown experience here](https://github.com/infinitered/ignite-cookbook/blob/universal-e2e-testing/docs/recipes/UniversalE2ETesting.md).
The end result should look something like this!
https://github.com/user-attachments/assets/a3f9886c-af52-4187-804b-080a40b29825
=> recipe: Universal E2E Testing with Detox and Playwright
