infinitered/ignite-cookbook

src/components/SVGImage/styles.module.css, src/css/custom.css, src/pages/index.tsx
The production build of the site adds some random characters to the end of the classname which messed up the style targeting. I'm going to do another PR to clean up and try to not use the `[class^='ABC']` syntax except when necessary.
https://user-images.githubusercontent.com/8878532/211581567-6369a7ae-9607-46eb-abd3-4f135401046c.mov
=> fix: updates css to target heroImage in production env

src/pages/index.tsx
The previous way we grabbed the docname for the link assumed it was a `.md` file. Now we just grab everything before the `.`
=> fix: changed how we grabbed link

docs/recipes/AccessibilityFontSizes.md
This PR fixes a simple typo in the `AccessibilityFontSizes` recipe. I guess the word was meant to be `how` but ended up as `mow`. I hope this is not intentional :).
=> Fixed a simple typo

docs/recipes/MaestroSetup.md
- Closes #74 
Also fixes recipe to scroll and find the requested RNR podcast. This failed because new episodes have been released and aren't visible in the `ScrollView` right away now.
=> fix(maestro-setup): app install instructions, added scroll actions

docs/recipes/TypeScriptBaseURL.md
- Fixes some small bash scripts that lacked syntax typing so we get the copy button
Before
After
- Updates the `tsconfig.json` edits to be more specific about the `compilerOptions` key
=> fix(typescript-base-url): some better snippet copying

docs/recipes/EASUpdate.md
Closes #78 
- Renames to EAS Update
- Title, description and resource changes to be more clear about the intentions of the recipe which are EAS Update and not upgrading the Expo SDK version in a project
=> fix: clarity for EAS Update over upgrading expo SDK version

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml
There was an issue where all the recipes where showing the last updated time being when the last pull request was merged. We just needed to change the clone depth of the action like so: https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951
=> fix(gh action): fixed clone depth

docs/recipes/SwitchBetweenExpoGoCNG.md
- Adds a new recipe for switching between Expo Go and Expo CNG Ignite workflows
Planning on referencing this recipe during Ignite workflow selection: 
```
✅ Do you want to use Expo? · Expo
📝 Which Expo workflow? (You can switch between them later with a little work -- here's how: https://ignitecookbook.com/docs/recipes/SwitchBetweenExpoGoCNG) … 
❯ Expo Go - For simple apps that don't need custom native code [Default]
Expo CNG - For more involved apps -- allows you to integrate custom native code via config plugins
```
=> feat(recipes): switch between expo go and cng

docs/recipes/Redux.md
- How to remove Mobx-State-Tree from Ignite default project
- How to add Redux, with example
- Persistence with redux-persist
- Point to Reactotron docs for installing `reactotron-redux` plugin
Closes #114
=> feat(recipes): redux recipe

docs/recipes/MaestroSetup.md
I ran into this when trying to use Maestro with an Expo Go app
=> fix: add expo instructions to maestro setup

docs/recipes/Redux.md, docs/recipes/RemoveMobxStateTree.md, docs/recipes/Zustand.md
I added a new recipe for migrating to Zustand and refactored the steps to remove Mobx-State-Tree out of the Redux post to be shared by both. 
The Redux recipe followed a `--removeDemo` project which was much simpler to convert. For Zustand I followed the Ignite Demo project, so this post includes a lot more detail on the actual process of converting models & state to Zustand. 
Open to thoughts on this - including the demo offers opportunity to learn about the differences between MST and Zustand, but it also adds a lot of extra length to this post which could be confusing for those starting from a demoless project.
=> feat(recipes): new Zustand recipe, and separate recipe for removing MobX-State-Tree

docusaurus.config.js
Issue on current site: documents often return incorrect `title`, because the code to find metadata ends with the _last_ found result of `title: x`. 
Several docs we have sample code that cause incorrect results, eg: 
```
reactotron.onCustomCommand({
title: "Go Back",
description: "Goes back",
command: "goBack",
```
This fix makes sure we only grab the first result found, which should always be at the top of a doc: 
```
---
title: Expo Router
description: How to convert Ignite v9 demo app to utilize `expo-router`
tags:
- Expo
- expo-router
- react-navigation
last_update:
author: Frank Calise & Justin Poliachik
publish_date: 2024-01-25
---
```
Screenshot after fix:
=> fix: metadata plugin should take first found result 

package.json, src/css/custom.css, yarn.lock
I noticed when searching for the "Expo Router" recipe that no result actually showed that title, even though the results linked to that page. An update to the local search library fixes this issue and displays the title under the header.
I think there are other improvements we can make to search, which I'll outline in another issue, but I think we're best off upgrading docusaurus to v3 first, since our best model for good search is reactnative.dev.
| **Before** | **After** |
| --- | --- |
| <img width=375 src="https://github.com/infinitered/ignite-cookbook/assets/5252268/db5a66e3-e536-4b91-b6c7-86de9f9d254e"> | <img width="375" alt="Screenshot 2024-02-14 at 2 22 09 PM" src="https://github.com/infinitered/ignite-cookbook/assets/5252268/8430574b-38fe-4284-aa5c-ae3d5a802842">  |
=> Show page titles in search

package.json, yarn.lock
For posterity, these are the reasons each of these resolutions was
added. They should all work fine; semver is a little concerning becuase
deps are depending on two different major versions there, but we can
only have a single resolution, but according to the changelog the only
breaking change was dropping support for older versions of node.
1. @babel/traverse: https://github.com/advisories/GHSA-67hx-6x53-jw92
```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@babel/traverse"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@babel/traverse@7.23.9"
info Has been hoisted to "@babel/traverse"
info Reasons this module exists
- Hoisted from "@docusaurus#core#@babel#traverse"
- Hoisted from …
```
=> Address dependabot alerts

docs/recipes/ExpoRouter.md
Thanks to @johnhamlin for raising an issue about this error that occurs when implementing this recipe! This PR adds in the necessary fixes to address it. https://github.com/infinitered/ignite-cookbook/issues/127
It also adds in a note about versioning in case someone accidentally uses the recipe in an older version of Expo.
=> Add note about Expo Router using v3 and fix ref issue in ListItem.tsx

docs/recipes/SampleYAMLCircleCI.md, src/components/LatestVersion/index.tsx, src/pages/index.module.css, src/pages/index.tsx
This feature dynamically displays the latest Ignite release on the homepage. It fetches release info from GitHub API, showing the version and how many days ago it was released and falls back to a generic GitHub link to `/latest/ if unable to fetch. 
This approach seemed simpler than trying to implement a GH Action or using a version badge for the same info, but if we're not happy to include an API call on this site let me know :)
I also included 2 small fixes I noticed while working on this.
=> Dynamically display ignite release versions

docs/recipes/ExpoRouter.md
Updated link to my updated repo, which contains the expo50 version example
=> fix: expo-router typo and link fix

docs/recipes/RequiringHardwareFeaturesWithExpo.md
This PR adds a new recipe called `Requiring Hardware Features with Expo`.
It shows the user how to add an expo config plugin to require specific hardware for the app to run.
=> feat(recipe): Adds new recipe for requiring specific device hardware

docs/recipes/MigratingToMMKV.md
This just makes things a little easier to read on which lines need to be added and deleted.
Before:
Now:
=> fix(mmkv): Add `success-line`s to the MMKV recipe so the diffs are easier to grok

docusaurus.config.ts, package.json, src/css/custom.css, yarn.lock
Addresses #58.
Minimal Algolia config, which also gives us automatic nesting of search result headers under their parent pages.
Notes on styles:
- Pre-existing styling logic doesn't apply cleanly to the new search component, and I got tired of trying to figure out Infima's intended usage (it's not very well-documented).
- Instead, I just updated the search box background to our background color instead of the cool gray it was, and decreased the default border radius, since the oval shape wasn't matched anywhere else.
Would be nice for the future:
- De-prioritize results from "Archive"
- More intentionally style the search component
=> Get Algolia working

docs/recipes/ExpoRouter.md
noticed this changed was something we needed to add after some RTL work on the `Toggle` component and recently following the recipe in 9.6.2
=> fix(expo-router): toggle component

docs/recipes/ReactNativeVisionCamera.md
Keeps `workflow` cli option in sync with the other recipes as we moved from `prebuild` to `cng`
=> fix(vision-camera): update param from prebuild to cng

src/components/LatestVersion/index.tsx, src/pages/index.module.css, src/pages/index.tsx
While I was reviewing a recipe, I noticed the new recipe title and Ignite title were not clickable. They were they same color as the links on the page and I kept trying to click them each time I visited.
Make the headers links for ease of navigation. Also align the text between the two columns so they have the same visual cadence. I'm using xScope for the guilds so you can seen the alignment.
| Before | After |
|--------|--------|
| <img width="1069" alt="image" src="https://github.com/infinitered/ignite-cookbook/assets/151139/56820f97-abbd-430e-b951-f210625946d4"> | <img width="1068" alt="image" src="https://github.com/infinitered/ignite-cookbook/assets/151139/57e8df0d-26b8-42e9-b7db-c1a0daa5e307"> |
| <video src="https://github.com/infinitered/ignite-cookbook/assets/151139/72d776fd-3da6- …
=> Making headers links and fixing text alignment

docs/recipes/MigratingToMMKV.md
Never removed the old package that we replaced inside the recipe xD
=> fix(mmkv): remove async storage pkg

docs/recipes/ExpoRouter.md
- Fixes an issue where you run into a run away effect, hitting max depth exceeded
- More details in the community thread here: https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1711401442775379
- Added `onPress` to the `Link` elements and removed `toggleDrawer` from `handleScroll`
=> fix(expo-router): showroom bug

docs/recipes/SelectFieldWithBottomSheet.mdx
- Fixes `spacing.large` constants to `spacing.lg` to reflect current Ignite styling better
=> fix(select-field): spacing constants

docs/recipes/Authentication.md
Many applications require an external service to authenticate the user. Setting up authentication for your application can feel daunting. Where do I start? What data do I need from my users? What service(s) should or could I use? What are the signup, signin, and other user flows that I'll need?
This recipe is going to use [Supabase](https://supabase.com/) as the backend. We'll build some primatives that will allow you to customize the authentication to your needs or existing backend service as well.
- Requirements
- Starting Point (Ignite)
- Build Initial Sign In Screen
- Environment Config
- Dependencies
- Session Storage
- Encrypting the User Session
- Creating and Managing the Session
- Initializing the Supabase Client
- Signing Up & Signing In
- Listening for Session Changes
- Loading …
=> COOK-1: Authentication with Supabase

docs/recipes/Authentication.md
- **Correct onPress action for sign up**
- **Denoting initial session storage and edits for encryption**
- **Adding missing error style**
- **Adding warning about environment variables with EAS build**
Thanks to @mazenchami for reporting these!
=> Tweaks to Authentication Recipe

docs/recipes/SelectFieldWithBottomSheet.mdx
- Fixes an issue where the Dismiss button for `<SelectField ... multiple />` runs up against the screen edge on smaller devices
=> style(select-field): dismiss button padding

docs/recipes/ExpoRouter.md, docs/recipes/GeneratorComponentTests.md
- Updates the Expo Router recipe to make updates to the generator templates with `destinationDir`
- Adds a note about support for dynamic paths coming soon to Ignite CLI for screens in a filed-base routing system
- Fixes a typo in Generator for Component Tests `frontmatter` => `front matter`
=> fix(expo-router): generators destinationDir

docs/recipes/MigratingToMMKV.md
I found the MMKV recipe a little hard to follow with all of the file adds/deletes in the `storage.ts` change, so i replaced it with a copy/pasta version to make things easier for those migrating.
=> chore: Update MMKV Recipe with full `storage.ts` example

docs/recipes/LocalFirstDataWithPowerSync.md
This updates the `PowerSync and Supabase for Local-First Data Management` recipe. The PowerSync SDK has been updated with many improvements which simplify the installation and usage. The changes here are to align the recipe with the latest SDK changes.
Some notable changes:
- Removed polyfill installation steps and Flipper network inspector step. This is no longer required since the SDK now pre-bundles polyfils and connects via WebSockets by default.
- Added Metro config step for inline requires. This seems to be required as highlighted here https://github.com/infinitered/ignite-cookbook/issues/175.
- Fixed minor inconsistencies in recipe code blocks. Some steps included importing code which is only created later in the guide.
- Updated hooks to use `useQuery` instead of the deprecated …
=> Docs: Update PowerSync Localfirst Recipe 

docs/recipes/Redux.md, docs/recipes/SelectFieldWithBottomSheet.mdx, docs/recipes/Theming-Emotion.mdx, docs/recipes/Theming-StyledComponents.mdx, docs/recipes/Theming-Unistyles.mdx, yarn.lock
Adds recipes for `styled-components`, `emotion.js`, and `unistyles` to integrate with the new theming system for Ignite.
This should not be merged until this PR is merged and released to production: https://github.com/infinitered/ignite/pull/2636
=> feat(Theming): Adds cookbook recipes for using the new theming system with various libraries

docs/recipes/Theming-Emotion.mdx, docs/recipes/Theming-StyledComponents.mdx, docs/recipes/Theming-Unistyles.mdx
I noticed the publish dates for a couple recipes were set in the future 😅
=> fix: incorrect publish dates for themeing recipes

docs/recipes/MonoreposOverview.md
This PR introduces part 1 of the pair of guides Infinite Red want to introduce around mono repo setups
[Part 2](https://github.com/infinitered/ignite-cookbook/pull/173) is in progress and is [awaiting improvements](https://github.com/infinitered/ignite-cookbook/pull/173#issuecomment-2496117350) in writing style for the monorepo guide. 
This PR's recipe includes guidance on choosing the right mono repo strategy, including when to adopt or avoid a mono repo, standard tools (Yarn Workspaces, Pnmp, Lerna, Nx, Turborepo), and typical setups that align with specific project needs.
=> Add choose right monorepo strategy recipe

docs/recipes/ReactNativeVisionCamera.md, docs/recipes/Zustand.md
Was looking into #136 and while the issue mentioned doesn't appear to be reproducible, there are a few areas of the recipe that were throwing/out of date. Moved to using the hooks API from react-native-vision-camera in lieu of the imperative API which we were already doing for the barcode scanning. 
Sources:
https://react-native-vision-camera.com/docs/guides#gettingrequesting-permissions
https://react-native-vision-camera.com/docs/guides/code-scanning
If you are contributing a recipe to this repository, you agree to license your contribution under the terms of the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.
If you have any questions, please reference the [CONTRIBUTING.md](../CONTRIBUTING.md) or [LICENSE.md](../LICENSE.md) file for more information.
Thank you …
=> recipe: update vision camera to use hooks

docs/recipes/SettingUpYarnMonorepo.md
- Fixes to the yarn monorepo recipe
- Global package.json script fix
- Fixes to the metro.config.js section
- Updates to the CLI prompt to reflect latest Ignite
=> fix(monorepo-yarn): metro fixes, CLI prompt changes, global script

docs/recipes/UpdatingIgnite.md
The spelling of Ignite, Ask and Go were mis-spelled.
If you are contributing a recipe to this repository, you agree to license your contribution under the terms of the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.
If you have any questions, please reference the [CONTRIBUTING.md](../CONTRIBUTING.md) or [LICENSE.md](../LICENSE.md) file for more information.
Thank you for your contribution!
=> Fixed 3 typos in UpdatingIgnite.md

docs/recipes/Authentication.md
@morganick  Added `// success-line` above `const { signOut } = useAuth()`, as that is a change that should be highlighted green.  _(I haven't tested the render locally.)_
For reference this is the original :
=> Minor edit: `const { signOut } = useAuth()` is missing a green highlight
